// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai/chat": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "向AI发送消息并获取非流式回复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "AI对话",
                "parameters": [
                    {
                        "description": "聊天消息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.aiChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对话成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.aiChatResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/ai/chat/stream": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "以SSE流式方式与AI助手对话，实时返回生成内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "AI流式聊天",
                "parameters": [
                    {
                        "description": "聊天消息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.aiChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE事件流",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/ai/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的AI画像条目（第二层记忆）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "获取AI画像",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.aiProfileResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/ai/summary/{convID}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为指定会话生成AI摘要",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "生成会话摘要",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "convID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "生成成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.aiSummaryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "使用用户名和密码登录，返回访问令牌和刷新令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.loginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "使用刷新令牌获取新的访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.refreshResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "令牌无效或已过期",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "使用用户名和密码注册新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.registerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "409": {
                        "description": "用户名已存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/avatar/{userID}": {
            "get": {
                "description": "返回用户头像图片。如果用户未设置头像，自动生成包含用户名首字母的 SVG 占位头像",
                "produces": [
                    "image/svg+xml"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户头像",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "用户ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名（用于生成默认头像首字母）",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "头像图片（SVG或重定向到图片URL）",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/friend/accept": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "接受指定ID的好友申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "接受好友申请",
                "parameters": [
                    {
                        "description": "接受信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.acceptFriendRequestReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "接受成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.acceptFriendRequestResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "无权操作",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "申请不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/friend/block": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将指定用户加入黑名单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "拉黑用户",
                "parameters": [
                    {
                        "description": "拉黑信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.blockUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "拉黑成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "409": {
                        "description": "已拉黑",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/friend/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的好友列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "获取好友列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/friend/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "拒绝指定ID的好友申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "拒绝好友申请",
                "parameters": [
                    {
                        "description": "拒绝信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.rejectFriendRequestReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "拒绝成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "无权操作",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "申请不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/friend/request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "向指定用户发送好友申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "发送好友申请",
                "parameters": [
                    {
                        "description": "申请信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.sendFriendRequestReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "申请发送成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.sendFriendRequestResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "409": {
                        "description": "已是好友或重复申请",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/friend/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的待处理好友申请列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "获取好友申请列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/friend/unblock": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将指定用户从黑名单中移除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "取消拉黑",
                "parameters": [
                    {
                        "description": "取消拉黑信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.unblockUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消拉黑成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/friend/{friendID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定ID的好友关系",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友"
                ],
                "summary": "删除好友",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "好友ID",
                        "name": "friendID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/group": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一个新群组，创建者自动成为群主",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "创建群组",
                "parameters": [
                    {
                        "description": "群组信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.createGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.createGroupResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/group/{groupID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据群组ID获取群组详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取群组信息",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "群组ID",
                        "name": "groupID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "群组不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新群组的名称和公告，仅群主或管理员可操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "更新群组信息",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "群组ID",
                        "name": "groupID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新群组信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.updateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "群组不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/group/{groupID}/leave": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "当前用户退出指定群组，群主不能直接退群（需先转让群主）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "退出群组",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "群组ID",
                        "name": "groupID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "群主不能退群",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "群组不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/group/{groupID}/member": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "向群组添加一名新成员，仅群主或管理员可操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "添加群成员",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "群组ID",
                        "name": "groupID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "成员信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.addMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "群组不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "409": {
                        "description": "已是成员或群组已满",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/group/{groupID}/member/{memberID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从群组中移除一名成员；若移除自己则为退群，移除他人则为踢出（仅群主/管理员可踢人）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "移除群成员",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "群组ID",
                        "name": "groupID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "成员ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "移除成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "群组不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/group/{groupID}/member/{memberID}/role": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新群组成员角色（普通成员/管理员），仅群主可操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "更新成员角色",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "群组ID",
                        "name": "groupID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "成员ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.updateMemberRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "群组不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/group/{groupID}/members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定群组的所有成员信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取群成员列表",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "群组ID",
                        "name": "groupID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/moment": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "发布一条新的朋友圈动态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "朋友圈"
                ],
                "summary": "发布动态",
                "parameters": [
                    {
                        "description": "动态内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.publishMomentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "发布成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.publishMomentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/moment/comment/{commentID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除自己发表的评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "朋友圈"
                ],
                "summary": "删除评论",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "评论ID",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.deleteCommentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "不是自己的评论",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "评论不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/moment/feed": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户好友的朋友圈动态流，支持游标分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "朋友圈"
                ],
                "summary": "获取朋友圈动态流",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分页游标（首页传空）",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量（默认20）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.momentFeedResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/moment/user/{userID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定用户发布的朋友圈动态列表，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "朋友圈"
                ],
                "summary": "获取用户动态列表",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "用户ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量（默认20）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "偏移量（默认0）",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/moment/{momentID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据动态ID获取单条动态的详细信息，包含点赞状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "朋友圈"
                ],
                "summary": "获取动态详情",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "动态ID",
                        "name": "momentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.getMomentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "动态不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/moment/{momentID}/comment": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对指定动态发表评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "朋友圈"
                ],
                "summary": "评论动态",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "动态ID",
                        "name": "momentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "评论内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.commentMomentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "评论成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.commentMomentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "动态不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/moment/{momentID}/like": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对指定动态进行点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "朋友圈"
                ],
                "summary": "点赞动态",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "动态ID",
                        "name": "momentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "点赞成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.likeMomentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "动态不存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "取消对指定动态的点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "朋友圈"
                ],
                "summary": "取消点赞",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "动态ID",
                        "name": "momentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消点赞成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.unlikeMomentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/msg/revoke": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "在2分钟内撤回已发送的消息，仅发送者可撤回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息操作"
                ],
                "summary": "撤回消息",
                "parameters": [
                    {
                        "description": "撤回请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.revokeMsgReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "撤回成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "消息不可撤回",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "403": {
                        "description": "非发送者",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/msg/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据关键词搜索用户的消息记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息操作"
                ],
                "summary": "搜索消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "返回数量限制",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "搜索结果",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/msg/{msgID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定的消息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息操作"
                ],
                "summary": "删除消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息ID",
                        "name": "msgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "convId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的通知偏好和免打扰设置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设置"
                ],
                "summary": "获取用户设置",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新当前用户的通知偏好和免打扰设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设置"
                ],
                "summary": "更新用户设置",
                "parameters": [
                    {
                        "description": "设置参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.updateSettingsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/settings/mute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将指定会话添加到免打扰列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设置"
                ],
                "summary": "添加免打扰会话",
                "parameters": [
                    {
                        "description": "会话ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.muteConvReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "409": {
                        "description": "会话已存在",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/settings/mute/{convID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将指定会话从免打扰列表中移除",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设置"
                ],
                "summary": "移除免打扰会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "convID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "移除成功",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "会话未找到",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        },
        "/upload/avatar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传用户头像图片，支持 jpg/png/gif/webp 格式",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "上传头像",
                "parameters": [
                    {
                        "type": "file",
                        "description": "头像图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_api.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api.uploadAvatarResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "文件格式不支持或文件过大",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.ApiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_api.acceptFriendRequestReq": {
            "type": "object",
            "required": [
                "request_id"
            ],
            "properties": {
                "request_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.acceptFriendRequestResp": {
            "type": "object",
            "properties": {
                "friend_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.addMemberRequest": {
            "type": "object",
            "required": [
                "member_id"
            ],
            "properties": {
                "member_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.aiChatRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "internal_api.aiChatResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string"
                }
            }
        },
        "internal_api.aiProfileItemDTO": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "field_name": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "internal_api.aiProfileResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.aiProfileItemDTO"
                    }
                }
            }
        },
        "internal_api.aiSummaryResponse": {
            "type": "object",
            "properties": {
                "conclusion": {
                    "type": "string"
                },
                "key_points": {
                    "type": "string"
                },
                "message_range": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "user_intent": {
                    "type": "string"
                }
            }
        },
        "internal_api.blockUserReq": {
            "type": "object",
            "required": [
                "blocked_id"
            ],
            "properties": {
                "blocked_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.commentMomentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "internal_api.commentMomentResponse": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.createGroupRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "notice": {
                    "type": "string"
                }
            }
        },
        "internal_api.createGroupResponse": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.deleteCommentResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "internal_api.getMomentResponse": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "description": "RFC3339 格式",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "like_count": {
                    "description": "点赞数",
                    "type": "integer"
                },
                "liked_by_me": {
                    "description": "当前用户是否已赞",
                    "type": "boolean"
                },
                "media_urls": {
                    "type": "string"
                },
                "visibility": {
                    "type": "integer"
                }
            }
        },
        "internal_api.likeMomentResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "最新点赞数",
                    "type": "integer"
                },
                "liked": {
                    "description": "操作后是否处于已赞状态",
                    "type": "boolean"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "internal_api.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_api.loginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_api.momentFeedResponse": {
            "type": "object",
            "properties": {
                "moments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.getMomentResponse"
                    }
                },
                "next_cursor": {
                    "description": "空串表示无更多",
                    "type": "string"
                }
            }
        },
        "internal_api.muteConvReq": {
            "type": "object",
            "required": [
                "convId"
            ],
            "properties": {
                "convId": {
                    "type": "string"
                }
            }
        },
        "internal_api.publishMomentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "media_urls": {
                    "description": "可空的 JSON 字符串",
                    "type": "string"
                },
                "visibility": {
                    "description": "1=全部, 2=好友, 3=私密",
                    "type": "integer"
                }
            }
        },
        "internal_api.publishMomentResponse": {
            "type": "object",
            "properties": {
                "moment_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.refreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_api.refreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                }
            }
        },
        "internal_api.registerRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_api.registerResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_api.rejectFriendRequestReq": {
            "type": "object",
            "required": [
                "request_id"
            ],
            "properties": {
                "request_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.revokeMsgReq": {
            "type": "object",
            "required": [
                "convId",
                "msgId"
            ],
            "properties": {
                "convId": {
                    "type": "string"
                },
                "msgId": {
                    "type": "integer"
                }
            }
        },
        "internal_api.sendFriendRequestReq": {
            "type": "object",
            "required": [
                "to_user_id"
            ],
            "properties": {
                "message": {
                    "type": "string"
                },
                "to_user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.sendFriendRequestResp": {
            "type": "object",
            "properties": {
                "from_user_id": {
                    "type": "integer"
                },
                "request_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "to_user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.unblockUserReq": {
            "type": "object",
            "required": [
                "blocked_id"
            ],
            "properties": {
                "blocked_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.unlikeMomentResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "liked": {
                    "type": "boolean"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "internal_api.updateGroupRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "notice": {
                    "type": "string"
                }
            }
        },
        "internal_api.updateMemberRoleRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "integer"
                }
            }
        },
        "internal_api.updateSettingsReq": {
            "type": "object",
            "properties": {
                "msg_preview_enabled": {
                    "type": "boolean"
                },
                "mute_list": {
                    "type": "string"
                },
                "notification_enabled": {
                    "type": "boolean"
                }
            }
        },
        "internal_api.uploadAvatarResponse": {
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "在 Authorization 头中携带 JWT 访问令牌，格式：Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GoIM API",
	Description:      "GoIM 即时通讯系统 API — 支持私聊、群聊、朋友圈动态、AI 助手。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
